- hosts: all
  gather_facts: true
  tasks:
      - name: Pobierz hostname hosta
        debug:
          msg: "Hostname: {{ ansible_hostname }}"
    - name: Pokaż system operacyjny
      debug:
        msg:
          - "OS: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "Release: {{ ansible_distribution_release }}"
