- hosts: all
  gather_facts: false
  tasks:
    - name: Pobierz tylko hostname i system operacyjny
      setup:
        filter:
          - "ansible_hostname"
          - "ansible_distribution"
          - "ansible_distribution_version"
          - "ansible_distribution_release"
          
    - name: Pobierz hostname hosta
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Pokaż system operacyjny
      debug:
        msg:
          - "OS: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "Release: {{ ansible_distribution_release }}"
